# SPDX-FileCopyrightText: 2020 Cam N. Coulter <cam@cncoulter.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Welcome to Jekyll (And Graph Paper)!
#
# If any field is marked as required, make sure you put in some value for it. If it's marked as required, that's because another page (such as SEO.html) assumes it's there, so if you leave the field blank, then your SEO settings (for example) will get messed up.

title: Graph Paper # Required.
url: "https://graphpaper.cncoulter.com" # Required.
baseurl: "" # the subpath of your site, e.g. /blog
description:
- Graph Paper is a Jekyll website integrated with Bootstrap and packed with features including support for multiple authors, featured images, tags, Twitter cards, and much more. If you want to design a website using Jekyll and Bootstrap, start by forking Graph Paper. # Required.
locale: en_US # Required.
timezone: America/Los_Angeles
author: Cam N. Coulter # Required.
email: cam@cncoulter.com
copyright: "Some rights reserved." # Required.
favicon: favicon.ico # Required. When forking, you will want to change this file to the favicon you will use for your site. If your favicon is placed in a subfolder (for example, `/img/config/`), then make sure to include the subfolder (for example, `favicon: config/favicon.ico`)

twitter: # Used for Twitter Cards
    card: summary # Required. "summary" or "summary_large_image"
    username: camncoulter # Not required. Twitter username for the website/publication

default_meta_image: notepad-593363_1920.jpg # Not required. This is the default image used for Twitter Cards. Image must be placed in /img/
default_meta_image_alt: "graph paper and a pen" # Required IF you have a default_meta_image

# Collections
collections_dir: collections
collections:
    people:
        output: true
        permalink: /people/:title/
    images:
        output: false

# Pagination
paginate: 3
paginate_path: "/blog/page:num/"

# Font Awesome
# Make your own account with Font Awesome and then replace the link below with your own kit’s code.
my_FA_kit: https://kit.fontawesome.com/b41e0c7e90.js # Required.

# Disqus Comments
disqus:
    # Leaving shortname blank will disable comments for your entire site.
    # To disable comments for any one page, include "comments: false" in the page's YAML front matter.
    shortname: graphpaper # Update this for your own site.

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Build settings
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: css
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
